### ISSUE TITLE
Serious problems in Internet Explorer

### ISSUE THREAD

**Issue by i-schuetz** [mdgriffith/style-elements#120]
I finished developing my homepage with style-elements, looks great in all browsers (tested on Chrome, Firefox, Safari, Opera and some mobile browsers) but in Internet Explorer and Edge (11) it's a mess. The main issue seems to be that the height of elements is not computed correctly.

The page is [ivanschuetz.com](http://ivanschuetz.com)

I can prepare small examples when I have time, but I'd appreciate some initial feedback, maybe something is already known or can be inferred from looking at the html.

**Comment by nelsonic** [comment]
@i-schuetz might be worth uploading screenshots of Chrome/FF vs. IE as _many_ people do not have _access_ the Microsoft browsers. 💡

**Comment by mdgriffith** [comment]
We spoke on slack, but I'm leaving a message here in case anyone happens upon this.

After some digging, this is due to css grid support being less than stellar for previous versions of Edge and current versions of IE.

To fix this, IE would need to improve it's support of css grids, though who knows if that will happen.

The best solution right now is to just use `row` and `column` to replace the `grid` element.

**Comment by i-schuetz** [comment]
I'm changing the layout from grid to rows/columns, in case anyone looks at the page in Internet Explorer. Soon everything will be replaced and the bugs not visible anymore. I'll actually remove the link to the page to avoid confusion.

**Comment by jethrolarson** [comment]
I found this library via https://www.youtube.com/watch?v=w4_1SagLY94 and I really wish his assertion that [if you use this library you support these browsers] held true. At the very least style-elements should be clear on which browsers and versions are supported so that users can make an informed decision.

**Comment by i-schuetz** [comment]
My personal opinion: Unless `grid` can be fixed (at least with a workaround) or mapped internally by style-elements to rows/columns, I'd just remove it (until IE supports it). Or maintain a "caniuse" for style-elements, but this probably goes against the goals of the library. Very little people will see the note that was added in #96.

**Comment by mdgriffith** [comment]
Adding a note and a link in the documentation makes sense.

Yeah, I'm actively considering removing `grid` in the long term, or at least replacing it with something that doesn't compile exactly to css grid.

There will be a browser compatibility table for style-elements at some point, obviously with the goal of having everything green.  It's a bit hard to verify an entire library, but there is some browser and testing automation that I've been working on that should get us most of the way there.
